[package]
name = "opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

glfw = "0.55"
gl = "0.14"
image = "0.24"
lazy_static = "1"
# russimp = {version = "3.2.0", features = ["prebuilt"]}